<?php

return [
    'roles' => [
        'platform-admin' => [
            'label' => 'Platform administrator',
            'permissions' => [
                'core.audit-logs.export',
                'core.audit-logs.view',
                'core.artifacts.manage',
                'core.artifacts.view',
                'core.events.view',
                'core.functional-actors.manage',
                'core.functional-actors.view',
                'core.menus.view',
                'core.notifications.manage',
                'core.notifications.view',
                'core.plugins.view',
                'core.plugins.manage',
                'core.permissions.view',
                'core.permissions.manage',
                'core.roles.view',
                'core.roles.manage',
                'core.tenancy.view',
                'core.tenancy.manage',
                'core.workflows.view',
            ],
        ],
        'hello-viewer' => [
            'label' => 'Hello world viewer',
            'permissions' => [
                'plugin.hello-world.hello.view',
            ],
        ],
        'asset-operator' => [
            'label' => 'Asset operator',
            'permissions' => [
                'plugin.asset-catalog.assets.view',
                'plugin.asset-catalog.assets.manage',
            ],
        ],
        'asset-viewer' => [
            'label' => 'Asset viewer',
            'permissions' => [
                'plugin.asset-catalog.assets.view',
            ],
        ],
        'actor-viewer' => [
            'label' => 'Functional actor viewer',
            'permissions' => [
                'plugin.actor-directory.actors.view',
            ],
        ],
        'control-operator' => [
            'label' => 'Control operator',
            'permissions' => [
                'plugin.controls-catalog.controls.view',
                'plugin.controls-catalog.controls.manage',
            ],
        ],
        'control-viewer' => [
            'label' => 'Control viewer',
            'permissions' => [
                'plugin.controls-catalog.controls.view',
            ],
        ],
        'risk-operator' => [
            'label' => 'Risk operator',
            'permissions' => [
                'plugin.risk-management.risks.view',
                'plugin.risk-management.risks.manage',
            ],
        ],
        'risk-viewer' => [
            'label' => 'Risk viewer',
            'permissions' => [
                'plugin.risk-management.risks.view',
            ],
        ],
        'findings-operator' => [
            'label' => 'Findings operator',
            'permissions' => [
                'plugin.findings-remediation.findings.view',
                'plugin.findings-remediation.findings.manage',
            ],
        ],
        'findings-viewer' => [
            'label' => 'Findings viewer',
            'permissions' => [
                'plugin.findings-remediation.findings.view',
            ],
        ],
        'policy-operator' => [
            'label' => 'Policy operator',
            'permissions' => [
                'plugin.policy-exceptions.policies.view',
                'plugin.policy-exceptions.policies.manage',
            ],
        ],
        'policy-viewer' => [
            'label' => 'Policy viewer',
            'permissions' => [
                'plugin.policy-exceptions.policies.view',
            ],
        ],
        'privacy-operator' => [
            'label' => 'Privacy operator',
            'permissions' => [
                'plugin.data-flows-privacy.records.view',
                'plugin.data-flows-privacy.records.manage',
            ],
        ],
        'privacy-viewer' => [
            'label' => 'Privacy viewer',
            'permissions' => [
                'plugin.data-flows-privacy.records.view',
            ],
        ],
        'continuity-operator' => [
            'label' => 'Continuity operator',
            'permissions' => [
                'plugin.continuity-bcm.plans.view',
                'plugin.continuity-bcm.plans.manage',
            ],
        ],
        'continuity-viewer' => [
            'label' => 'Continuity viewer',
            'permissions' => [
                'plugin.continuity-bcm.plans.view',
            ],
        ],
        'identity-operator' => [
            'label' => 'Identity operator',
            'permissions' => [
                'plugin.identity-local.users.view',
                'plugin.identity-local.users.manage',
                'plugin.identity-local.memberships.view',
                'plugin.identity-local.memberships.manage',
            ],
        ],
        'identity-viewer' => [
            'label' => 'Identity viewer',
            'permissions' => [
                'plugin.identity-local.users.view',
                'plugin.identity-local.memberships.view',
            ],
        ],
    ],
    'grants' => [
        [
            'target_type' => 'principal',
            'target_id' => 'principal-admin',
            'grant_type' => 'role',
            'value' => 'platform-admin',
            'context_type' => 'platform',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-hello',
            'grant_type' => 'role',
            'value' => 'hello-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-hello',
            'grant_type' => 'role',
            'value' => 'asset-operator',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-hello',
            'grant_type' => 'role',
            'value' => 'actor-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-hello',
            'grant_type' => 'role',
            'value' => 'control-operator',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-hello',
            'grant_type' => 'role',
            'value' => 'risk-operator',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-hello',
            'grant_type' => 'role',
            'value' => 'findings-operator',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-hello',
            'grant_type' => 'role',
            'value' => 'policy-operator',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-hello',
            'grant_type' => 'role',
            'value' => 'privacy-operator',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-hello',
            'grant_type' => 'role',
            'value' => 'continuity-operator',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-hello',
            'grant_type' => 'role',
            'value' => 'identity-operator',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-viewer',
            'grant_type' => 'role',
            'value' => 'asset-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-viewer',
            'grant_type' => 'role',
            'value' => 'actor-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-viewer',
            'grant_type' => 'role',
            'value' => 'control-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-viewer',
            'grant_type' => 'role',
            'value' => 'risk-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-viewer',
            'grant_type' => 'role',
            'value' => 'findings-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-viewer',
            'grant_type' => 'role',
            'value' => 'policy-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-viewer',
            'grant_type' => 'role',
            'value' => 'privacy-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-viewer',
            'grant_type' => 'role',
            'value' => 'continuity-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-a-viewer',
            'grant_type' => 'role',
            'value' => 'identity-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-a',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-b-ops',
            'grant_type' => 'role',
            'value' => 'asset-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-b',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-b-ops',
            'grant_type' => 'role',
            'value' => 'actor-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-b',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-b-ops',
            'grant_type' => 'role',
            'value' => 'control-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-b',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-b-ops',
            'grant_type' => 'role',
            'value' => 'risk-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-b',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-b-ops',
            'grant_type' => 'role',
            'value' => 'findings-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-b',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-b-ops',
            'grant_type' => 'role',
            'value' => 'privacy-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-b',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-b-ops',
            'grant_type' => 'role',
            'value' => 'continuity-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-b',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-b-ops',
            'grant_type' => 'role',
            'value' => 'identity-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-b',
        ],
        [
            'target_type' => 'membership',
            'target_id' => 'membership-org-b-ops',
            'grant_type' => 'role',
            'value' => 'policy-viewer',
            'context_type' => 'organization',
            'organization_id' => 'org-b',
        ],
    ],
];
