<?php

namespace PymeSec\Plugins\AutomationCatalog\Runtime;

class GenericPackRuntimeExecutor implements AutomationPackRuntimeExecutorInterface
{
    public function supports(array $pack): bool
    {
        return true;
    }

    public function generateEvidencePayload(array $pack, array $mapping, array $target, array $context): array
    {
        $packKey = (string) ($pack['pack_key'] ?? 'unknown-pack');
        $subjectType = (string) ($target['subject_type'] ?? 'unknown-subject');
        $subjectId = (string) ($target['subject_id'] ?? 'unknown-id');
        $mappingLabel = (string) ($mapping['mapping_label'] ?? 'Runtime mapping');
        $trigger = (string) ($context['trigger_mode'] ?? 'manual');
        $timestamp = (string) ($context['run_started_at'] ?? now()->toDateTimeString());
        $changeFingerprint = hash('sha256', implode('|', [
            'generic-v1',
            $packKey,
            $mappingLabel,
            $subjectType,
            $subjectId,
        ]));

        return [
            'status' => 'success',
            'check_outcome' => 'pass',
            'severity' => 'info',
            'change_fingerprint' => $changeFingerprint,
            'artifact_type' => 'report',
            'label' => sprintf('%s runtime report', $mappingLabel),
            'filename' => sprintf(
                '%s-%s-%s-runtime-report.txt',
                str_replace('.', '-', $packKey),
                $subjectType,
                preg_replace('/[^a-zA-Z0-9_-]+/', '-', $subjectId) ?: 'subject'
            ),
            'content' => implode(PHP_EOL, [
                'PymeSec Automation Runtime Report',
                sprintf('Pack: %s', $packKey),
                sprintf('Mapping: %s', $mappingLabel),
                sprintf('Target: %s:%s', $subjectType, $subjectId),
                sprintf('Trigger: %s', $trigger),
                sprintf('Timestamp: %s', $timestamp),
                'Result: baseline runtime payload generated by generic executor.',
            ]).PHP_EOL,
            'message' => sprintf('Runtime evidence generated for %s:%s.', $subjectType, $subjectId),
        ];
    }
}
