<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CoreTenancySeeder extends Seeder
{
    public function run(): void
    {
        $roles = [];
        $rolePermissions = [];
        $grants = [];

        foreach (config('authorization.roles', []) as $key => $role) {
            if (! is_string($key) || ! is_array($role)) {
                continue;
            }

            $roles[] = [
                'key' => $key,
                'label' => (string) ($role['label'] ?? $key),
                'is_system' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ];

            foreach (array_values(array_filter(
                $role['permissions'] ?? [],
                static fn (mixed $permission): bool => is_string($permission) && $permission !== '',
            )) as $permission) {
                $rolePermissions[] = [
                    'role_key' => $key,
                    'permission_key' => $permission,
                ];
            }
        }

        foreach (config('authorization.grants', []) as $index => $grant) {
            if (! is_array($grant)) {
                continue;
            }

            $targetType = $grant['target_type'] ?? null;
            $targetId = $grant['target_id'] ?? null;
            $grantType = $grant['grant_type'] ?? null;
            $value = $grant['value'] ?? null;
            $contextType = $grant['context_type'] ?? null;

            if (! is_string($targetType) || ! is_string($targetId) || ! is_string($grantType) || ! is_string($value) || ! is_string($contextType)) {
                continue;
            }

            $grants[] = [
                'id' => sprintf('seed-grant-%03d', $index + 1),
                'target_type' => $targetType,
                'target_id' => $targetId,
                'grant_type' => $grantType,
                'value' => $value,
                'context_type' => $contextType,
                'organization_id' => is_string($grant['organization_id'] ?? null) ? $grant['organization_id'] : null,
                'scope_id' => is_string($grant['scope_id'] ?? null) ? $grant['scope_id'] : null,
                'is_system' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        DB::table('authorization_roles')->insertOrIgnore($roles);
        DB::table('authorization_role_permissions')->insertOrIgnore($rolePermissions);
        DB::table('authorization_grants')->insertOrIgnore($grants);

        DB::table('organizations')->insertOrIgnore([
            [
                'id' => 'org-a',
                'name' => 'Northwind Manufacturing',
                'slug' => 'northwind-manufacturing',
                'default_locale' => 'en',
                'default_timezone' => 'Europe/Madrid',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'org-b',
                'name' => 'Bluewave Logistics',
                'slug' => 'bluewave-logistics',
                'default_locale' => 'en',
                'default_timezone' => 'Europe/Berlin',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('scopes')->insertOrIgnore([
            [
                'id' => 'scope-eu',
                'organization_id' => 'org-a',
                'name' => 'Europe Perimeter',
                'slug' => 'europe-perimeter',
                'description' => 'European operational perimeter for shared assets and assessments.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'scope-it',
                'organization_id' => 'org-a',
                'name' => 'IT Services',
                'slug' => 'it-services',
                'description' => 'Internal IT service perimeter.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'scope-ops',
                'organization_id' => 'org-b',
                'name' => 'Operations Hub',
                'slug' => 'operations-hub',
                'description' => 'Primary logistics and warehouse perimeter.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('memberships')->insertOrIgnore([
            [
                'id' => 'membership-org-a-hello',
                'principal_id' => 'principal-org-a',
                'organization_id' => 'org-a',
                'roles' => json_encode(['asset-operator', 'hello-viewer', 'identity-operator'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'membership-org-a-viewer',
                'principal_id' => 'principal-org-a',
                'organization_id' => 'org-a',
                'roles' => json_encode(['asset-viewer', 'identity-viewer'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'membership-org-b-ops',
                'principal_id' => 'principal-org-a',
                'organization_id' => 'org-b',
                'roles' => json_encode(['asset-viewer', 'identity-viewer'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('membership_scope')->insertOrIgnore([
            [
                'membership_id' => 'membership-org-b-ops',
                'scope_id' => 'scope-ops',
            ],
        ]);

        DB::table('assets')->insertOrIgnore([
            [
                'id' => 'asset-erp-prod',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'name' => 'ERP Production',
                'type' => 'application',
                'criticality' => 'high',
                'classification' => 'confidential',
                'owner_label' => 'Finance Operations',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'asset-vault-docs',
                'organization_id' => 'org-a',
                'scope_id' => null,
                'name' => 'Document Vault',
                'type' => 'storage',
                'criticality' => 'medium',
                'classification' => 'restricted',
                'owner_label' => 'Compliance Office',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'asset-laptop-fleet',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'name' => 'Managed Laptop Fleet',
                'type' => 'endpoint',
                'criticality' => 'medium',
                'classification' => 'internal',
                'owner_label' => 'IT Services',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'asset-warehouse-mesh',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'name' => 'Warehouse Mesh',
                'type' => 'network',
                'criticality' => 'high',
                'classification' => 'restricted',
                'owner_label' => 'Operations Control',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'asset-route-planner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'name' => 'Route Planner',
                'type' => 'application',
                'criticality' => 'medium',
                'classification' => 'internal',
                'owner_label' => 'Logistics Team',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('control_frameworks')->insertOrIgnore([
            [
                'id' => 'framework-iso-27001',
                'organization_id' => 'org-a',
                'code' => 'ISO 27001',
                'name' => 'ISO 27001:2022',
                'description' => 'Core information security management requirements and Annex A controls.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'framework-nis2',
                'organization_id' => 'org-a',
                'code' => 'NIS2',
                'name' => 'NIS2',
                'description' => 'Operational resilience and cybersecurity obligations for essential entities.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'framework-soc-2',
                'organization_id' => 'org-b',
                'code' => 'SOC 2',
                'name' => 'SOC 2',
                'description' => 'Trust services criteria for security and operations monitoring.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('control_requirements')->insertOrIgnore([
            [
                'id' => 'requirement-iso-a-5-18',
                'organization_id' => 'org-a',
                'framework_id' => 'framework-iso-27001',
                'code' => 'A.5.18',
                'title' => 'Access rights',
                'description' => 'Access rights should be provisioned and reviewed according to business need.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'requirement-iso-a-8-15',
                'organization_id' => 'org-a',
                'framework_id' => 'framework-iso-27001',
                'code' => 'A.8.15',
                'title' => 'Logging',
                'description' => 'Event logging should support traceability and investigations.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'requirement-nis2-backup-testing',
                'organization_id' => 'org-a',
                'framework_id' => 'framework-nis2',
                'code' => 'Article 21',
                'title' => 'Business continuity and backup management',
                'description' => 'Organizations should maintain continuity capability and test backup resilience.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'requirement-soc2-cc7-2',
                'organization_id' => 'org-b',
                'framework_id' => 'framework-soc-2',
                'code' => 'CC7.2',
                'title' => 'System monitoring',
                'description' => 'Monitoring controls should detect anomalies and unauthorized activity.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('controls')->insertOrIgnore([
            [
                'id' => 'control-access-review',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'framework_id' => 'framework-iso-27001',
                'name' => 'Quarterly Access Review',
                'framework' => 'ISO 27001',
                'domain' => 'Identity',
                'evidence' => 'Access certification pack',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'control-backup-governance',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'framework_id' => 'framework-nis2',
                'name' => 'Backup Governance',
                'framework' => 'NIS2',
                'domain' => 'Resilience',
                'evidence' => 'Backup policy and restore tests',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'control-route-integrity',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'framework_id' => 'framework-soc-2',
                'name' => 'Route Integrity Monitoring',
                'framework' => 'SOC 2',
                'domain' => 'Operations',
                'evidence' => 'Telemetry reviews',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('control_requirement_mappings')->insertOrIgnore([
            [
                'id' => 'mapping-control-access-review-iso-a-5-18',
                'organization_id' => 'org-a',
                'control_id' => 'control-access-review',
                'requirement_id' => 'requirement-iso-a-5-18',
                'coverage' => 'full',
                'notes' => 'Quarterly certification covers approval, review, and recertification checkpoints.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'mapping-control-access-review-iso-a-8-15',
                'organization_id' => 'org-a',
                'control_id' => 'control-access-review',
                'requirement_id' => 'requirement-iso-a-8-15',
                'coverage' => 'partial',
                'notes' => 'Review evidence supports traceability but depends on logging controls elsewhere.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'mapping-control-backup-governance-nis2',
                'organization_id' => 'org-a',
                'control_id' => 'control-backup-governance',
                'requirement_id' => 'requirement-nis2-backup-testing',
                'coverage' => 'full',
                'notes' => 'Backup governance includes test cadence and recovery readiness evidence.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'mapping-control-route-integrity-soc2',
                'organization_id' => 'org-b',
                'control_id' => 'control-route-integrity',
                'requirement_id' => 'requirement-soc2-cc7-2',
                'coverage' => 'full',
                'notes' => 'Telemetry reviews demonstrate continuous operational monitoring.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('risks')->insertOrIgnore([
            [
                'id' => 'risk-access-drift',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'title' => 'Privileged access drift',
                'category' => 'Identity',
                'inherent_score' => 20,
                'residual_score' => 10,
                'linked_asset_id' => 'asset-erp-prod',
                'linked_control_id' => 'control-access-review',
                'treatment' => 'Quarterly certification and emergency access review.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'risk-backup-assurance',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'title' => 'Restore assurance gap',
                'category' => 'Resilience',
                'inherent_score' => 16,
                'residual_score' => 8,
                'linked_asset_id' => 'asset-laptop-fleet',
                'linked_control_id' => 'control-backup-governance',
                'treatment' => 'Evidence monthly restore tests and tighten backup ownership.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'risk-route-blackout',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'title' => 'Route telemetry blackout',
                'category' => 'Operations',
                'inherent_score' => 18,
                'residual_score' => 9,
                'linked_asset_id' => 'asset-route-planner',
                'linked_control_id' => 'control-route-integrity',
                'treatment' => 'Correlate route planner telemetry with warehouse monitoring.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('findings')->insertOrIgnore([
            [
                'id' => 'finding-access-review-gap',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'title' => 'Access review evidence gap',
                'severity' => 'high',
                'description' => 'Reviewer evidence for the quarterly access certification is incomplete for privileged roles.',
                'linked_control_id' => 'control-access-review',
                'linked_risk_id' => 'risk-access-drift',
                'due_on' => now()->addDays(14)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'finding-backup-test-gap',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'title' => 'Restore test traceability gap',
                'severity' => 'medium',
                'description' => 'Monthly restore test outcomes are not linked to the governing control set.',
                'linked_control_id' => 'control-backup-governance',
                'linked_risk_id' => 'risk-backup-assurance',
                'due_on' => now()->addDays(21)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'finding-route-monitoring-gap',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'title' => 'Route monitoring escalation gap',
                'severity' => 'high',
                'description' => 'Escalation coverage for route telemetry blackouts is not consistently documented.',
                'linked_control_id' => 'control-route-integrity',
                'linked_risk_id' => 'risk-route-blackout',
                'due_on' => now()->addDays(10)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('remediation_actions')->insertOrIgnore([
            [
                'id' => 'action-access-review-pack',
                'finding_id' => 'finding-access-review-gap',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'title' => 'Publish signed reviewer evidence pack',
                'status' => 'planned',
                'notes' => 'Upload reviewer sign-off and exception notes to the finding.',
                'due_on' => now()->addDays(7)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'action-restore-test-linkage',
                'finding_id' => 'finding-backup-test-gap',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'title' => 'Link restore tests to control evidence',
                'status' => 'in-progress',
                'notes' => 'Map restore test outputs to the control review package.',
                'due_on' => now()->addDays(12)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'action-route-escalation-runbook',
                'finding_id' => 'finding-route-monitoring-gap',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'title' => 'Document telemetry escalation runbook',
                'status' => 'planned',
                'notes' => 'Define notification thresholds and on-call handoff.',
                'due_on' => now()->addDays(5)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('policies')->insertOrIgnore([
            [
                'id' => 'policy-access-governance',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'title' => 'Access Governance Policy',
                'area' => 'Identity',
                'version_label' => 'v1.4',
                'statement' => 'Privileged access must be reviewed quarterly and emergency entitlements must be justified and logged.',
                'linked_control_id' => 'control-access-review',
                'review_due_on' => now()->addDays(30)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'policy-backup-assurance',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'title' => 'Backup Assurance Policy',
                'area' => 'Resilience',
                'version_label' => 'v2.1',
                'statement' => 'Critical restore procedures must be tested monthly and linked to evidence retained by the control owner.',
                'linked_control_id' => 'control-backup-governance',
                'review_due_on' => now()->addDays(45)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'policy-route-telemetry',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'title' => 'Route Telemetry Escalation Policy',
                'area' => 'Operations',
                'version_label' => 'v1.2',
                'statement' => 'Telemetry outages affecting route planning must be escalated within defined warehouse and logistics thresholds.',
                'linked_control_id' => 'control-route-integrity',
                'review_due_on' => now()->addDays(20)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('policy_exceptions')->insertOrIgnore([
            [
                'id' => 'exception-break-glass-window',
                'policy_id' => 'policy-access-governance',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'title' => 'Extended break-glass review window',
                'rationale' => 'Quarter-end finance close requires a temporary extension of emergency access certification windows.',
                'compensating_control' => 'Daily review by compliance office during the extended window.',
                'linked_finding_id' => 'finding-access-review-gap',
                'expires_on' => now()->addDays(14)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'exception-restore-lab-gap',
                'policy_id' => 'policy-backup-assurance',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'title' => 'Restore lab availability exception',
                'rationale' => 'The secondary restore lab is under rebuild and monthly restore testing is being executed in a reduced environment.',
                'compensating_control' => 'Capture manual restore walkthroughs and management approval until the lab returns.',
                'linked_finding_id' => 'finding-backup-test-gap',
                'expires_on' => now()->addDays(21)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'exception-route-alert-window',
                'policy_id' => 'policy-route-telemetry',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'title' => 'Telemetry alert consolidation exception',
                'rationale' => 'Operations is consolidating route alerts into a new runbook and needs a temporary tolerance window.',
                'compensating_control' => 'Warehouse control room performs manual escalation checks twice per shift.',
                'linked_finding_id' => 'finding-route-monitoring-gap',
                'expires_on' => now()->addDays(10)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('privacy_data_flows')->insertOrIgnore([
            [
                'id' => 'data-flow-customer-support-handoff',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'title' => 'Customer support handoff',
                'source' => 'CRM platform',
                'destination' => 'Support operations',
                'data_category_summary' => 'Customer identifiers, case notes, and order references.',
                'transfer_type' => 'internal',
                'review_due_on' => now()->addDays(18)->toDateString(),
                'linked_asset_id' => 'asset-erp-prod',
                'linked_risk_id' => 'risk-access-drift',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'data-flow-backup-vendor-transfer',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'title' => 'Backup vendor transfer',
                'source' => 'Backup orchestration',
                'destination' => 'Restore lab vendor',
                'data_category_summary' => 'System metadata, contact details, and recovery identifiers.',
                'transfer_type' => 'vendor',
                'review_due_on' => now()->addDays(24)->toDateString(),
                'linked_asset_id' => 'asset-laptop-fleet',
                'linked_risk_id' => 'risk-backup-assurance',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'data-flow-route-telemetry-export',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'title' => 'Route telemetry export',
                'source' => 'Route planner',
                'destination' => 'Warehouse control room',
                'data_category_summary' => 'Driver identifiers, route events, and incident escalation context.',
                'transfer_type' => 'internal',
                'review_due_on' => now()->addDays(12)->toDateString(),
                'linked_asset_id' => 'asset-route-planner',
                'linked_risk_id' => 'risk-route-blackout',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('privacy_processing_activities')->insertOrIgnore([
            [
                'id' => 'processing-activity-customer-support-operations',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'title' => 'Customer support operations',
                'purpose' => 'Handle support requests, triage incidents, and coordinate customer case resolution.',
                'lawful_basis' => 'contract',
                'linked_data_flow_ids' => 'data-flow-customer-support-handoff',
                'linked_risk_ids' => 'risk-access-drift',
                'linked_policy_id' => 'policy-access-governance',
                'linked_finding_id' => 'finding-access-review-gap',
                'review_due_on' => now()->addDays(20)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'processing-activity-restore-assurance',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'title' => 'Restore assurance coordination',
                'purpose' => 'Coordinate restore testing and vendor validation of continuity records.',
                'lawful_basis' => 'legal-obligation',
                'linked_data_flow_ids' => 'data-flow-backup-vendor-transfer',
                'linked_risk_ids' => 'risk-backup-assurance',
                'linked_policy_id' => 'policy-backup-assurance',
                'linked_finding_id' => 'finding-backup-test-gap',
                'review_due_on' => now()->addDays(28)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'processing-activity-route-monitoring',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'title' => 'Route monitoring and escalation',
                'purpose' => 'Monitor route disruptions and coordinate escalations affecting warehouse operations.',
                'lawful_basis' => 'legitimate-interests',
                'linked_data_flow_ids' => 'data-flow-route-telemetry-export',
                'linked_risk_ids' => 'risk-route-blackout',
                'linked_policy_id' => 'policy-route-telemetry',
                'linked_finding_id' => 'finding-route-monitoring-gap',
                'review_due_on' => now()->addDays(16)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('continuity_services')->insertOrIgnore([
            [
                'id' => 'continuity-service-customer-support',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'title' => 'Customer Support Operations',
                'impact_tier' => 'high',
                'recovery_time_objective_hours' => 8,
                'recovery_point_objective_hours' => 2,
                'linked_asset_id' => 'asset-erp-prod',
                'linked_risk_id' => 'risk-access-drift',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'continuity-service-backup-recovery',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'title' => 'Backup and Recovery Operations',
                'impact_tier' => 'critical',
                'recovery_time_objective_hours' => 4,
                'recovery_point_objective_hours' => 1,
                'linked_asset_id' => 'asset-laptop-fleet',
                'linked_risk_id' => 'risk-backup-assurance',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'continuity-service-route-control',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'title' => 'Route Control Room',
                'impact_tier' => 'critical',
                'recovery_time_objective_hours' => 2,
                'recovery_point_objective_hours' => 1,
                'linked_asset_id' => 'asset-route-planner',
                'linked_risk_id' => 'risk-route-blackout',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('continuity_recovery_plans')->insertOrIgnore([
            [
                'id' => 'continuity-plan-support-fallback',
                'service_id' => 'continuity-service-customer-support',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'title' => 'Support fallback rota',
                'strategy_summary' => 'Move case intake to the fallback rota and re-route high impact tickets within one shift.',
                'test_due_on' => now()->addDays(21)->toDateString(),
                'linked_policy_id' => 'policy-access-governance',
                'linked_finding_id' => 'finding-access-review-gap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'continuity-plan-restore-bridge',
                'service_id' => 'continuity-service-backup-recovery',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'title' => 'Restore bridge activation',
                'strategy_summary' => 'Activate the restore bridge runbook and switch recovery validation to the alternate environment.',
                'test_due_on' => now()->addDays(14)->toDateString(),
                'linked_policy_id' => 'policy-backup-assurance',
                'linked_finding_id' => 'finding-backup-test-gap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'continuity-plan-route-manual-control',
                'service_id' => 'continuity-service-route-control',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'title' => 'Manual route control handoff',
                'strategy_summary' => 'Switch route escalation to manual control room procedures until telemetry normalizes.',
                'test_due_on' => now()->addDays(9)->toDateString(),
                'linked_policy_id' => 'policy-route-telemetry',
                'linked_finding_id' => 'finding-route-monitoring-gap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('functional_actors')->insertOrIgnore([
            [
                'id' => 'actor-finance-ops',
                'provider' => 'actor-directory',
                'kind' => 'team',
                'display_name' => 'Finance Operations',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode([
                    'title' => 'Asset owner team',
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'actor-compliance-office',
                'provider' => 'actor-directory',
                'kind' => 'team',
                'display_name' => 'Compliance Office',
                'organization_id' => 'org-a',
                'scope_id' => null,
                'metadata' => json_encode([
                    'title' => 'Shared governance owner',
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'actor-it-services',
                'provider' => 'actor-directory',
                'kind' => 'team',
                'display_name' => 'IT Services',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode([
                    'title' => 'Endpoint operations owner',
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'actor-ava-mason',
                'provider' => 'actor-directory',
                'kind' => 'person',
                'display_name' => 'Ava Mason',
                'organization_id' => 'org-a',
                'scope_id' => null,
                'metadata' => json_encode([
                    'title' => 'Compliance manager',
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'actor-operations-control',
                'provider' => 'actor-directory',
                'kind' => 'team',
                'display_name' => 'Operations Control',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode([
                    'title' => 'Warehouse operations owner',
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'actor-logistics-team',
                'provider' => 'actor-directory',
                'kind' => 'team',
                'display_name' => 'Logistics Team',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode([
                    'title' => 'Route planning owner',
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('principal_functional_actor_links')->insertOrIgnore([
            [
                'id' => 'link-principal-org-a-ava-mason',
                'principal_id' => 'principal-org-a',
                'functional_actor_id' => 'actor-ava-mason',
                'organization_id' => 'org-a',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('functional_assignments')->insertOrIgnore([
            [
                'id' => 'assignment-asset-erp-owner',
                'functional_actor_id' => 'actor-finance-ops',
                'domain_object_type' => 'asset',
                'domain_object_id' => 'asset-erp-prod',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-asset-vault-owner',
                'functional_actor_id' => 'actor-compliance-office',
                'domain_object_type' => 'asset',
                'domain_object_id' => 'asset-vault-docs',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => null,
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-asset-laptop-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'asset',
                'domain_object_id' => 'asset-laptop-fleet',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-asset-warehouse-owner',
                'functional_actor_id' => 'actor-operations-control',
                'domain_object_type' => 'asset',
                'domain_object_id' => 'asset-warehouse-mesh',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-asset-route-owner',
                'functional_actor_id' => 'actor-logistics-team',
                'domain_object_type' => 'asset',
                'domain_object_id' => 'asset-route-planner',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-control-access-owner',
                'functional_actor_id' => 'actor-ava-mason',
                'domain_object_type' => 'control',
                'domain_object_id' => 'control-access-review',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-control-backup-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'control',
                'domain_object_id' => 'control-backup-governance',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-control-route-owner',
                'functional_actor_id' => 'actor-operations-control',
                'domain_object_type' => 'control',
                'domain_object_id' => 'control-route-integrity',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-risk-access-owner',
                'functional_actor_id' => 'actor-ava-mason',
                'domain_object_type' => 'risk',
                'domain_object_id' => 'risk-access-drift',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-risk-backup-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'risk',
                'domain_object_id' => 'risk-backup-assurance',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-risk-route-owner',
                'functional_actor_id' => 'actor-operations-control',
                'domain_object_type' => 'risk',
                'domain_object_id' => 'risk-route-blackout',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-finding-access-owner',
                'functional_actor_id' => 'actor-ava-mason',
                'domain_object_type' => 'finding',
                'domain_object_id' => 'finding-access-review-gap',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-finding-backup-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'finding',
                'domain_object_id' => 'finding-backup-test-gap',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-finding-route-owner',
                'functional_actor_id' => 'actor-operations-control',
                'domain_object_type' => 'finding',
                'domain_object_id' => 'finding-route-monitoring-gap',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-action-access-owner',
                'functional_actor_id' => 'actor-compliance-office',
                'domain_object_type' => 'remediation-action',
                'domain_object_id' => 'action-access-review-pack',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-action-backup-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'remediation-action',
                'domain_object_id' => 'action-restore-test-linkage',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-action-route-owner',
                'functional_actor_id' => 'actor-logistics-team',
                'domain_object_type' => 'remediation-action',
                'domain_object_id' => 'action-route-escalation-runbook',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-policy-access-owner',
                'functional_actor_id' => 'actor-compliance-office',
                'domain_object_type' => 'policy',
                'domain_object_id' => 'policy-access-governance',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-policy-backup-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'policy',
                'domain_object_id' => 'policy-backup-assurance',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-policy-route-owner',
                'functional_actor_id' => 'actor-operations-control',
                'domain_object_type' => 'policy',
                'domain_object_id' => 'policy-route-telemetry',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-exception-access-owner',
                'functional_actor_id' => 'actor-ava-mason',
                'domain_object_type' => 'policy-exception',
                'domain_object_id' => 'exception-break-glass-window',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-exception-backup-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'policy-exception',
                'domain_object_id' => 'exception-restore-lab-gap',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-exception-route-owner',
                'functional_actor_id' => 'actor-logistics-team',
                'domain_object_type' => 'policy-exception',
                'domain_object_id' => 'exception-route-alert-window',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-data-flow-support-owner',
                'functional_actor_id' => 'actor-compliance-office',
                'domain_object_type' => 'privacy-data-flow',
                'domain_object_id' => 'data-flow-customer-support-handoff',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-data-flow-backup-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'privacy-data-flow',
                'domain_object_id' => 'data-flow-backup-vendor-transfer',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-data-flow-route-owner',
                'functional_actor_id' => 'actor-operations-control',
                'domain_object_type' => 'privacy-data-flow',
                'domain_object_id' => 'data-flow-route-telemetry-export',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-privacy-activity-support-owner',
                'functional_actor_id' => 'actor-ava-mason',
                'domain_object_type' => 'privacy-processing-activity',
                'domain_object_id' => 'processing-activity-customer-support-operations',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-privacy-activity-restore-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'privacy-processing-activity',
                'domain_object_id' => 'processing-activity-restore-assurance',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-privacy-activity-route-owner',
                'functional_actor_id' => 'actor-logistics-team',
                'domain_object_type' => 'privacy-processing-activity',
                'domain_object_id' => 'processing-activity-route-monitoring',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-continuity-service-support-owner',
                'functional_actor_id' => 'actor-ava-mason',
                'domain_object_type' => 'continuity-service',
                'domain_object_id' => 'continuity-service-customer-support',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-continuity-service-backup-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'continuity-service',
                'domain_object_id' => 'continuity-service-backup-recovery',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-continuity-service-route-owner',
                'functional_actor_id' => 'actor-operations-control',
                'domain_object_type' => 'continuity-service',
                'domain_object_id' => 'continuity-service-route-control',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-continuity-plan-support-owner',
                'functional_actor_id' => 'actor-compliance-office',
                'domain_object_type' => 'continuity-plan',
                'domain_object_id' => 'continuity-plan-support-fallback',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-continuity-plan-restore-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'continuity-plan',
                'domain_object_id' => 'continuity-plan-restore-bridge',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-continuity-plan-route-owner',
                'functional_actor_id' => 'actor-logistics-team',
                'domain_object_type' => 'continuity-plan',
                'domain_object_id' => 'continuity-plan-route-manual-control',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
