<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CoreTenancySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('organizations')->insertOrIgnore([
            [
                'id' => 'org-a',
                'name' => 'Northwind Manufacturing',
                'slug' => 'northwind-manufacturing',
                'default_locale' => 'en',
                'default_timezone' => 'Europe/Madrid',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'org-b',
                'name' => 'Bluewave Logistics',
                'slug' => 'bluewave-logistics',
                'default_locale' => 'en',
                'default_timezone' => 'Europe/Berlin',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('scopes')->insertOrIgnore([
            [
                'id' => 'scope-eu',
                'organization_id' => 'org-a',
                'name' => 'Europe Perimeter',
                'slug' => 'europe-perimeter',
                'description' => 'European operational perimeter for shared assets and assessments.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'scope-it',
                'organization_id' => 'org-a',
                'name' => 'IT Services',
                'slug' => 'it-services',
                'description' => 'Internal IT service perimeter.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'scope-ops',
                'organization_id' => 'org-b',
                'name' => 'Operations Hub',
                'slug' => 'operations-hub',
                'description' => 'Primary logistics and warehouse perimeter.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('memberships')->insertOrIgnore([
            [
                'id' => 'membership-org-a-hello',
                'principal_id' => 'principal-org-a',
                'organization_id' => 'org-a',
                'roles' => json_encode(['asset-operator', 'hello-viewer'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'membership-org-a-viewer',
                'principal_id' => 'principal-org-a',
                'organization_id' => 'org-a',
                'roles' => json_encode(['asset-viewer'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'membership-org-b-ops',
                'principal_id' => 'principal-org-a',
                'organization_id' => 'org-b',
                'roles' => json_encode(['asset-viewer'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('membership_scope')->insertOrIgnore([
            [
                'membership_id' => 'membership-org-b-ops',
                'scope_id' => 'scope-ops',
            ],
        ]);

        DB::table('controls')->insertOrIgnore([
            [
                'id' => 'control-access-review',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'name' => 'Quarterly Access Review',
                'framework' => 'ISO 27001',
                'domain' => 'Identity',
                'evidence' => 'Access certification pack',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'control-backup-governance',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'name' => 'Backup Governance',
                'framework' => 'NIS2',
                'domain' => 'Resilience',
                'evidence' => 'Backup policy and restore tests',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'control-route-integrity',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'name' => 'Route Integrity Monitoring',
                'framework' => 'SOC 2',
                'domain' => 'Operations',
                'evidence' => 'Telemetry reviews',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('risks')->insertOrIgnore([
            [
                'id' => 'risk-access-drift',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'title' => 'Privileged access drift',
                'category' => 'Identity',
                'inherent_score' => 20,
                'residual_score' => 10,
                'linked_asset_id' => 'asset-erp-prod',
                'linked_control_id' => 'control-access-review',
                'treatment' => 'Quarterly certification and emergency access review.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'risk-backup-assurance',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'title' => 'Restore assurance gap',
                'category' => 'Resilience',
                'inherent_score' => 16,
                'residual_score' => 8,
                'linked_asset_id' => 'asset-laptop-fleet',
                'linked_control_id' => 'control-backup-governance',
                'treatment' => 'Evidence monthly restore tests and tighten backup ownership.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'risk-route-blackout',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'title' => 'Route telemetry blackout',
                'category' => 'Operations',
                'inherent_score' => 18,
                'residual_score' => 9,
                'linked_asset_id' => 'asset-route-planner',
                'linked_control_id' => 'control-route-integrity',
                'treatment' => 'Correlate route planner telemetry with warehouse monitoring.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('findings')->insertOrIgnore([
            [
                'id' => 'finding-access-review-gap',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'title' => 'Access review evidence gap',
                'severity' => 'high',
                'description' => 'Reviewer evidence for the quarterly access certification is incomplete for privileged roles.',
                'linked_control_id' => 'control-access-review',
                'linked_risk_id' => 'risk-access-drift',
                'due_on' => now()->addDays(14)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'finding-backup-test-gap',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'title' => 'Restore test traceability gap',
                'severity' => 'medium',
                'description' => 'Monthly restore test outcomes are not linked to the governing control set.',
                'linked_control_id' => 'control-backup-governance',
                'linked_risk_id' => 'risk-backup-assurance',
                'due_on' => now()->addDays(21)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'finding-route-monitoring-gap',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'title' => 'Route monitoring escalation gap',
                'severity' => 'high',
                'description' => 'Escalation coverage for route telemetry blackouts is not consistently documented.',
                'linked_control_id' => 'control-route-integrity',
                'linked_risk_id' => 'risk-route-blackout',
                'due_on' => now()->addDays(10)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('remediation_actions')->insertOrIgnore([
            [
                'id' => 'action-access-review-pack',
                'finding_id' => 'finding-access-review-gap',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'title' => 'Publish signed reviewer evidence pack',
                'status' => 'planned',
                'notes' => 'Upload reviewer sign-off and exception notes to the finding.',
                'due_on' => now()->addDays(7)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'action-restore-test-linkage',
                'finding_id' => 'finding-backup-test-gap',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'title' => 'Link restore tests to control evidence',
                'status' => 'in-progress',
                'notes' => 'Map restore test outputs to the control review package.',
                'due_on' => now()->addDays(12)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'action-route-escalation-runbook',
                'finding_id' => 'finding-route-monitoring-gap',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'title' => 'Document telemetry escalation runbook',
                'status' => 'planned',
                'notes' => 'Define notification thresholds and on-call handoff.',
                'due_on' => now()->addDays(5)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('policies')->insertOrIgnore([
            [
                'id' => 'policy-access-governance',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'title' => 'Access Governance Policy',
                'area' => 'Identity',
                'version_label' => 'v1.4',
                'statement' => 'Privileged access must be reviewed quarterly and emergency entitlements must be justified and logged.',
                'linked_control_id' => 'control-access-review',
                'review_due_on' => now()->addDays(30)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'policy-backup-assurance',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'title' => 'Backup Assurance Policy',
                'area' => 'Resilience',
                'version_label' => 'v2.1',
                'statement' => 'Critical restore procedures must be tested monthly and linked to evidence retained by the control owner.',
                'linked_control_id' => 'control-backup-governance',
                'review_due_on' => now()->addDays(45)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'policy-route-telemetry',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'title' => 'Route Telemetry Escalation Policy',
                'area' => 'Operations',
                'version_label' => 'v1.2',
                'statement' => 'Telemetry outages affecting route planning must be escalated within defined warehouse and logistics thresholds.',
                'linked_control_id' => 'control-route-integrity',
                'review_due_on' => now()->addDays(20)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('policy_exceptions')->insertOrIgnore([
            [
                'id' => 'exception-break-glass-window',
                'policy_id' => 'policy-access-governance',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'title' => 'Extended break-glass review window',
                'rationale' => 'Quarter-end finance close requires a temporary extension of emergency access certification windows.',
                'compensating_control' => 'Daily review by compliance office during the extended window.',
                'linked_finding_id' => 'finding-access-review-gap',
                'expires_on' => now()->addDays(14)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'exception-restore-lab-gap',
                'policy_id' => 'policy-backup-assurance',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'title' => 'Restore lab availability exception',
                'rationale' => 'The secondary restore lab is under rebuild and monthly restore testing is being executed in a reduced environment.',
                'compensating_control' => 'Capture manual restore walkthroughs and management approval until the lab returns.',
                'linked_finding_id' => 'finding-backup-test-gap',
                'expires_on' => now()->addDays(21)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'exception-route-alert-window',
                'policy_id' => 'policy-route-telemetry',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'title' => 'Telemetry alert consolidation exception',
                'rationale' => 'Operations is consolidating route alerts into a new runbook and needs a temporary tolerance window.',
                'compensating_control' => 'Warehouse control room performs manual escalation checks twice per shift.',
                'linked_finding_id' => 'finding-route-monitoring-gap',
                'expires_on' => now()->addDays(10)->toDateString(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('functional_actors')->insertOrIgnore([
            [
                'id' => 'actor-finance-ops',
                'provider' => 'actor-directory',
                'kind' => 'team',
                'display_name' => 'Finance Operations',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode([
                    'title' => 'Asset owner team',
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'actor-compliance-office',
                'provider' => 'actor-directory',
                'kind' => 'team',
                'display_name' => 'Compliance Office',
                'organization_id' => 'org-a',
                'scope_id' => null,
                'metadata' => json_encode([
                    'title' => 'Shared governance owner',
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'actor-it-services',
                'provider' => 'actor-directory',
                'kind' => 'team',
                'display_name' => 'IT Services',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode([
                    'title' => 'Endpoint operations owner',
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'actor-ava-mason',
                'provider' => 'actor-directory',
                'kind' => 'person',
                'display_name' => 'Ava Mason',
                'organization_id' => 'org-a',
                'scope_id' => null,
                'metadata' => json_encode([
                    'title' => 'Compliance manager',
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'actor-operations-control',
                'provider' => 'actor-directory',
                'kind' => 'team',
                'display_name' => 'Operations Control',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode([
                    'title' => 'Warehouse operations owner',
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'actor-logistics-team',
                'provider' => 'actor-directory',
                'kind' => 'team',
                'display_name' => 'Logistics Team',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode([
                    'title' => 'Route planning owner',
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('principal_functional_actor_links')->insertOrIgnore([
            [
                'id' => 'link-principal-org-a-ava-mason',
                'principal_id' => 'principal-org-a',
                'functional_actor_id' => 'actor-ava-mason',
                'organization_id' => 'org-a',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('functional_assignments')->insertOrIgnore([
            [
                'id' => 'assignment-asset-erp-owner',
                'functional_actor_id' => 'actor-finance-ops',
                'domain_object_type' => 'asset',
                'domain_object_id' => 'asset-erp-prod',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-asset-vault-owner',
                'functional_actor_id' => 'actor-compliance-office',
                'domain_object_type' => 'asset',
                'domain_object_id' => 'asset-vault-docs',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => null,
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-asset-laptop-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'asset',
                'domain_object_id' => 'asset-laptop-fleet',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-asset-warehouse-owner',
                'functional_actor_id' => 'actor-operations-control',
                'domain_object_type' => 'asset',
                'domain_object_id' => 'asset-warehouse-mesh',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-asset-route-owner',
                'functional_actor_id' => 'actor-logistics-team',
                'domain_object_type' => 'asset',
                'domain_object_id' => 'asset-route-planner',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-control-access-owner',
                'functional_actor_id' => 'actor-ava-mason',
                'domain_object_type' => 'control',
                'domain_object_id' => 'control-access-review',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-control-backup-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'control',
                'domain_object_id' => 'control-backup-governance',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-control-route-owner',
                'functional_actor_id' => 'actor-operations-control',
                'domain_object_type' => 'control',
                'domain_object_id' => 'control-route-integrity',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-risk-access-owner',
                'functional_actor_id' => 'actor-ava-mason',
                'domain_object_type' => 'risk',
                'domain_object_id' => 'risk-access-drift',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-risk-backup-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'risk',
                'domain_object_id' => 'risk-backup-assurance',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-risk-route-owner',
                'functional_actor_id' => 'actor-operations-control',
                'domain_object_type' => 'risk',
                'domain_object_id' => 'risk-route-blackout',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-finding-access-owner',
                'functional_actor_id' => 'actor-ava-mason',
                'domain_object_type' => 'finding',
                'domain_object_id' => 'finding-access-review-gap',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-finding-backup-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'finding',
                'domain_object_id' => 'finding-backup-test-gap',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-finding-route-owner',
                'functional_actor_id' => 'actor-operations-control',
                'domain_object_type' => 'finding',
                'domain_object_id' => 'finding-route-monitoring-gap',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-action-access-owner',
                'functional_actor_id' => 'actor-compliance-office',
                'domain_object_type' => 'remediation-action',
                'domain_object_id' => 'action-access-review-pack',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-action-backup-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'remediation-action',
                'domain_object_id' => 'action-restore-test-linkage',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-action-route-owner',
                'functional_actor_id' => 'actor-logistics-team',
                'domain_object_type' => 'remediation-action',
                'domain_object_id' => 'action-route-escalation-runbook',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode([
                    'source' => 'seed',
                ], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-policy-access-owner',
                'functional_actor_id' => 'actor-compliance-office',
                'domain_object_type' => 'policy',
                'domain_object_id' => 'policy-access-governance',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-policy-backup-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'policy',
                'domain_object_id' => 'policy-backup-assurance',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-policy-route-owner',
                'functional_actor_id' => 'actor-operations-control',
                'domain_object_type' => 'policy',
                'domain_object_id' => 'policy-route-telemetry',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-exception-access-owner',
                'functional_actor_id' => 'actor-ava-mason',
                'domain_object_type' => 'policy-exception',
                'domain_object_id' => 'exception-break-glass-window',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-eu',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-exception-backup-owner',
                'functional_actor_id' => 'actor-it-services',
                'domain_object_type' => 'policy-exception',
                'domain_object_id' => 'exception-restore-lab-gap',
                'assignment_type' => 'owner',
                'organization_id' => 'org-a',
                'scope_id' => 'scope-it',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'assignment-exception-route-owner',
                'functional_actor_id' => 'actor-logistics-team',
                'domain_object_type' => 'policy-exception',
                'domain_object_id' => 'exception-route-alert-window',
                'assignment_type' => 'owner',
                'organization_id' => 'org-b',
                'scope_id' => 'scope-ops',
                'metadata' => json_encode(['source' => 'seed'], JSON_THROW_ON_ERROR),
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
